-- 0024_demo_catalogus
--
-- GEGENEREERD door `scripts/seed-sql.mjs` in de factum-webshop-repo.
-- Niet met de hand bewerken: pas `data/catalog.mjs` aan en genereer opnieuw.
--
-- Vervangt de oude werkplekartikelen door het assortiment dat de winkel nu
-- toont: de modulaire AI- en softwareproducten van FactumAI. De tabellen en
-- kolommen uit 0005 blijven ongewijzigd — een "order" is hier een
-- implementatietraject en `tracking` zijn de mijlpalen daarvan.
--
-- Idempotent: opnieuw draaien werkt de rijen bij en ruimt op wat weg is.

-- ---------------------------------------------------------------------------
-- Artikelen
-- ---------------------------------------------------------------------------
insert into public.demo_inventory
  (sku, product_name, category, in_stock, unit_value, lead_time_days, data)
values
  ('FA-AGT-MAIL', 'Mailagent', 'Agents', 1, 750, 14, '{"sku":"FA-AGT-MAIL","slug":"mailagent","productName":"Mailagent","category":"Agents","tagline":"Klantenservicemail voorbereid, altijd langs een mens","summary":"Leest je klantenservicemailbox, zoekt de feiten op in je eigen systemen en schrijft een conceptantwoord. Jouw medewerker keurt goed, past aan of wijst af — pas daarna gaat er iets de deur uit.","priceOnce":4500,"priceMonthly":750,"priceLabel":"€ 4.500 eenmalig + € 750 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":14,"requires":["Microsoft 365 / Exchange"],"url":"/producten/mailagent"}'::jsonb),
  ('FA-AGT-CHAT', 'Chatbot', 'Agents', 1, 450, 10, '{"sku":"FA-AGT-CHAT","slug":"chatbot","productName":"Chatbot","category":"Agents","tagline":"De widget op je site, met dezelfde grenzen","summary":"Eén regel script op je site. Beantwoordt direct wat uit je systemen of je kennisbank komt, en maakt een ticket van alles wat een handeling vraagt.","priceOnce":2500,"priceMonthly":450,"priceLabel":"€ 2.500 eenmalig + € 450 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":10,"requires":[],"url":"/producten/chatbot"}'::jsonb),
  ('FA-AGT-WA', 'WhatsApp-agent', 'Agents', 1, 550, 21, '{"sku":"FA-AGT-WA","slug":"whatsapp-agent","productName":"WhatsApp-agent","category":"Agents","tagline":"Hetzelfde gesprek, ander kanaal","summary":"Klantcontact via WhatsApp Business, op dezelfde lus en in dezelfde werkbak als mail en chat.","priceOnce":2500,"priceMonthly":550,"priceLabel":"€ 2.500 eenmalig + € 550 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":21,"requires":[],"url":"/producten/whatsapp-agent"}'::jsonb),
  ('FA-AGT-DOC', 'Documentagent', 'Agents', 1, 650, 14, '{"sku":"FA-AGT-DOC","slug":"documentagent","productName":"Documentagent","category":"Agents","tagline":"Inkomende pdf omgezet naar gestructureerde gegevens","summary":"Leest facturen, pakbonnen en inkooporders uit binnenkomende mail en zet ze om naar velden die je systeem begrijpt. Bij twijfel naar een mens.","priceOnce":3500,"priceMonthly":650,"priceLabel":"€ 3.500 eenmalig + € 650 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":14,"requires":[],"url":"/producten/documentagent"}'::jsonb),
  ('FA-AGT-TEL', 'Telefonie-agent', 'Agents', 0, 950, 30, '{"sku":"FA-AGT-TEL","slug":"telefonie-agent","productName":"Telefonie-agent","category":"Agents","tagline":"Opnemen, uitvragen, samenvatten","summary":"Neemt op buiten kantoortijd, vraagt uit wat nodig is en levert een samenvatting plus ticket op. Draait bij een handvol klanten.","priceOnce":6000,"priceMonthly":950,"priceLabel":"€ 6.000 eenmalig + € 950 per maand","availability":"beta","availabilityLabel":"Bèta","leadTimeDays":30,"requires":["Ticketing"],"url":"/producten/telefonie-agent"}'::jsonb),
  ('FA-KOP-M365', 'Microsoft 365 / Exchange', 'Koppelingen', 1, 1200, 5, '{"sku":"FA-KOP-M365","slug":"koppeling-m365","productName":"Microsoft 365 / Exchange","category":"Koppelingen","tagline":"Mail, agenda en contactpersonen via Graph","summary":"Lezen en versturen vanuit een gedeelde mailbox, plus agenda en contactpersonen. De standaardkoppeling onder de mailagent.","priceOnce":1200,"priceMonthly":0,"priceLabel":"€ 1.200 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-m365"}'::jsonb),
  ('FA-KOP-GWS', 'Google Workspace', 'Koppelingen', 1, 1200, 5, '{"sku":"FA-KOP-GWS","slug":"koppeling-google","productName":"Google Workspace","category":"Koppelingen","tagline":"Gmail en Google Agenda","summary":"Zelfde functionaliteit als de Microsoft-koppeling, andere leverancier.","priceOnce":1200,"priceMonthly":0,"priceLabel":"€ 1.200 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-google"}'::jsonb),
  ('FA-KOP-WOO', 'WooCommerce', 'Koppelingen', 1, 1200, 5, '{"sku":"FA-KOP-WOO","slug":"koppeling-woocommerce","productName":"WooCommerce","category":"Koppelingen","tagline":"Orders, klanten, producten en voorraad","summary":"De agent kan een order opzoeken, de status zien en de voorraad van een artikel opvragen. Alleen-lezen tenzij je schrijfacties aanzet.","priceOnce":1200,"priceMonthly":0,"priceLabel":"€ 1.200 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-woocommerce"}'::jsonb),
  ('FA-KOP-SHOP', 'Shopify', 'Koppelingen', 1, 1200, 5, '{"sku":"FA-KOP-SHOP","slug":"koppeling-shopify","productName":"Shopify","category":"Koppelingen","tagline":"Orders, fulfilment en klantgegevens","summary":"Zelfde als de WooCommerce-koppeling, op de Admin API van Shopify.","priceOnce":1200,"priceMonthly":0,"priceLabel":"€ 1.200 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-shopify"}'::jsonb),
  ('FA-KOP-EOL', 'Exact Online', 'Koppelingen', 1, 1800, 10, '{"sku":"FA-KOP-EOL","slug":"koppeling-exact","productName":"Exact Online","category":"Koppelingen","tagline":"Facturen, debiteuren en openstaande posten","summary":"Voor factuurvragen: welke factuur, welk bedrag, betaald of niet. Duurder dan de andere koppelingen omdat de OAuth-inrichting per administratie gaat.","priceOnce":1800,"priceMonthly":0,"priceLabel":"€ 1.800 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":10,"requires":[],"url":"/producten/koppeling-exact"}'::jsonb),
  ('FA-KOP-HUB', 'HubSpot', 'Koppelingen', 1, 1400, 5, '{"sku":"FA-KOP-HUB","slug":"koppeling-hubspot","productName":"HubSpot","category":"Koppelingen","tagline":"Contactpersonen, deals en de tijdlijn","summary":"De agent weet met wie hij praat en wat er eerder is gebeurd, en kan het gesprek op de tijdlijn zetten.","priceOnce":1400,"priceMonthly":0,"priceLabel":"€ 1.400 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-hubspot"}'::jsonb),
  ('FA-KOP-PIPE', 'Pipedrive', 'Koppelingen', 1, 1400, 5, '{"sku":"FA-KOP-PIPE","slug":"koppeling-pipedrive","productName":"Pipedrive","category":"Koppelingen","tagline":"Personen, organisaties en deals","summary":"Zelfde rol als de HubSpot-koppeling, andere leverancier.","priceOnce":1400,"priceMonthly":0,"priceLabel":"€ 1.400 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/koppeling-pipedrive"}'::jsonb),
  ('FA-KOP-STRP', 'Stripe', 'Koppelingen', 1, 900, 3, '{"sku":"FA-KOP-STRP","slug":"koppeling-stripe","productName":"Stripe","category":"Koppelingen","tagline":"Betalingen, terugbetalingen en abonnementen","summary":"Voor betaalvragen: is er betaald, wanneer, en met welke methode. Terugbetalen blijft handwerk.","priceOnce":900,"priceMonthly":0,"priceLabel":"€ 900 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":3,"requires":[],"url":"/producten/koppeling-stripe"}'::jsonb),
  ('FA-KOP-MOL', 'Mollie', 'Koppelingen', 1, 900, 3, '{"sku":"FA-KOP-MOL","slug":"koppeling-mollie","productName":"Mollie","category":"Koppelingen","tagline":"iDEAL, Bancontact en de rest","summary":"Zelfde als de Stripe-koppeling, voor wie via Mollie int.","priceOnce":900,"priceMonthly":0,"priceLabel":"€ 900 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":3,"requires":[],"url":"/producten/koppeling-mollie"}'::jsonb),
  ('FA-KOP-TRACK', 'PostNL & DHL', 'Koppelingen', 1, 800, 3, '{"sku":"FA-KOP-TRACK","slug":"koppeling-vervoerders","productName":"PostNL & DHL","category":"Koppelingen","tagline":"Track & trace zonder naar de vervoerder te sturen","summary":"De agent haalt de bezorgstatus op en vertelt hem in gewone taal, in plaats van een link te sturen.","priceOnce":800,"priceMonthly":0,"priceLabel":"€ 800 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":3,"requires":[],"url":"/producten/koppeling-vervoerders"}'::jsonb),
  ('FA-KOP-KVK', 'KVK Handelsregister', 'Koppelingen', 1, 600, 2, '{"sku":"FA-KOP-KVK","slug":"koppeling-kvk","productName":"KVK Handelsregister","category":"Koppelingen","tagline":"Bedrijfsgegevens bij een zakelijke aanvraag","summary":"Vult bij een zakelijke aanvraag automatisch de officiële bedrijfsgegevens aan, zodat je collega niet zit te zoeken.","priceOnce":600,"priceMonthly":0,"priceLabel":"€ 600 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":2,"requires":[],"url":"/producten/koppeling-kvk"}'::jsonb),
  ('FA-KOP-CUST', 'Maatwerkkoppeling', 'Koppelingen', 0, 2500, 14, '{"sku":"FA-KOP-CUST","slug":"koppeling-maatwerk","productName":"Maatwerkkoppeling","category":"Koppelingen","tagline":"Voor het systeem dat hier niet bij staat","summary":"Heeft je systeem een API of een export, dan kunnen we erop koppelen. Vanaf € 2.500 — het echte bedrag komt uit een half uur kijken.","priceOnce":2500,"priceMonthly":0,"priceLabel":"€ 2.500 eenmalig","availability":"aanvraag","availabilityLabel":"Op aanvraag","leadTimeDays":14,"requires":[],"url":"/producten/koppeling-maatwerk"}'::jsonb),
  ('FA-MOD-BAK', 'Werkbak', 'Modules', 1, 0, 0, '{"sku":"FA-MOD-BAK","slug":"module-werkbak","productName":"Werkbak","category":"Modules","tagline":"Waar je team het werk doet","summary":"De cockpit waarin concepten worden goedgekeurd. Zit standaard bij elke agent — je hoeft hem niet apart te kopen.","priceOnce":0,"priceMonthly":0,"priceLabel":"Inbegrepen","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":0,"requires":[],"url":"/producten/module-werkbak"}'::jsonb),
  ('FA-MOD-KB', 'Kennisbank', 'Modules', 1, 250, 7, '{"sku":"FA-MOD-KB","slug":"module-kennisbank","productName":"Kennisbank","category":"Modules","tagline":"Je eigen documenten als bron","summary":"Handleidingen, voorwaarden en eerdere antwoorden worden doorzoekbaar, zodat de agent uit jouw teksten put in plaats van uit algemene kennis.","priceOnce":1500,"priceMonthly":250,"priceLabel":"€ 1.500 eenmalig + € 250 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":7,"requires":[],"url":"/producten/module-kennisbank"}'::jsonb),
  ('FA-MOD-TIC', 'Ticketing', 'Modules', 1, 200, 2, '{"sku":"FA-MOD-TIC","slug":"module-ticketing","productName":"Ticketing","category":"Modules","tagline":"Voor alles wat een handeling vraagt","summary":"Een retour, een wijziging, een klacht: de agent maakt er een ticket van met de context er al bij, en geeft de klant een nummer.","priceOnce":0,"priceMonthly":200,"priceLabel":"€ 200 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":2,"requires":[],"url":"/producten/module-ticketing"}'::jsonb),
  ('FA-MOD-RAP', 'Rapportage', 'Modules', 1, 150, 2, '{"sku":"FA-MOD-RAP","slug":"module-rapportage","productName":"Rapportage","category":"Modules","tagline":"Wat er binnenkomt, en wat de agent ermee deed","summary":"Volume per categorie, hoeveel concepten ongewijzigd de deur uit gingen, waar je team het vaakst corrigeert.","priceOnce":0,"priceMonthly":150,"priceLabel":"€ 150 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":2,"requires":[],"url":"/producten/module-rapportage"}'::jsonb),
  ('FA-MOD-AUD', 'Auditlog & compliance-export', 'Modules', 1, 175, 2, '{"sku":"FA-MOD-AUD","slug":"module-auditlog","productName":"Auditlog & compliance-export","category":"Modules","tagline":"Aantoonbaar wie wat wanneer goedkeurde","summary":"Onveranderlijke vastlegging van elke beslissing, met export voor een audit of een AVG-verzoek.","priceOnce":0,"priceMonthly":175,"priceLabel":"€ 175 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":2,"requires":[],"url":"/producten/module-auditlog"}'::jsonb),
  ('FA-MOD-LANG', 'Meertaligheid', 'Modules', 1, 125, 2, '{"sku":"FA-MOD-LANG","slug":"module-meertalig","productName":"Meertaligheid","category":"Modules","tagline":"Antwoorden in de taal van het bericht","summary":"Herkent de taal van de klant en antwoordt in dezelfde taal, met je eigen toon per taal.","priceOnce":0,"priceMonthly":125,"priceLabel":"€ 125 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":2,"requires":[],"url":"/producten/module-meertalig"}'::jsonb),
  ('FA-MOD-SSO', 'Single sign-on', 'Modules', 1, 100, 5, '{"sku":"FA-MOD-SSO","slug":"module-sso","productName":"Single sign-on","category":"Modules","tagline":"Inloggen op de werkbak met je eigen account","summary":"Entra ID of Google Workspace als inlog voor de werkbak, inclusief automatisch afsluiten bij uitdiensttreding.","priceOnce":750,"priceMonthly":100,"priceLabel":"€ 750 eenmalig + € 100 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/module-sso"}'::jsonb),
  ('FA-DNS-DISC', 'Discovery', 'Diensten', 1, 1500, 5, '{"sku":"FA-DNS-DISC","slug":"dienst-discovery","productName":"Discovery","category":"Diensten","tagline":"Uitzoeken wat er eigenlijk binnenkomt","summary":"Een dagdeel meekijken in je mailbox en je bestaande antwoorden, met een rapport: welke onderwerpen, welke volumes, wat is haalbaar.","priceOnce":1500,"priceMonthly":0,"priceLabel":"€ 1.500 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":5,"requires":[],"url":"/producten/dienst-discovery"}'::jsonb),
  ('FA-DNS-IMPL', 'Implementatie & inrichting', 'Diensten', 1, 4500, 21, '{"sku":"FA-DNS-IMPL","slug":"dienst-implementatie","productName":"Implementatie & inrichting","category":"Diensten","tagline":"Wij richten in, niet jij","summary":"Categorieën, beleid per categorie, tone of voice, twee standaardkoppelingen en het meelopen tijdens de eerste weken.","priceOnce":4500,"priceMonthly":0,"priceLabel":"€ 4.500 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":21,"requires":[],"url":"/producten/dienst-implementatie"}'::jsonb),
  ('FA-DNS-TRAIN', 'Training werkbak', 'Diensten', 1, 850, 7, '{"sku":"FA-DNS-TRAIN","slug":"dienst-training","productName":"Training werkbak","category":"Diensten","tagline":"Een halve dag met het team dat ermee gaat werken","summary":"Hoe je goedkeurt, wanneer je aanpast en wanneer je afwijst — en waarom dat laatste net zo waardevol is.","priceOnce":850,"priceMonthly":0,"priceLabel":"€ 850 eenmalig","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":7,"requires":[],"url":"/producten/dienst-training"}'::jsonb),
  ('FA-DNS-SLA-Z', 'Support-SLA Zilver', 'Diensten', 1, 300, 0, '{"sku":"FA-DNS-SLA-Z","slug":"dienst-sla-zilver","productName":"Support-SLA Zilver","category":"Diensten","tagline":"Reactie binnen vier uur op werkdagen","summary":"Boven op de standaardsupport: kortere reactietijd en een vaste contactpersoon.","priceOnce":0,"priceMonthly":300,"priceLabel":"€ 300 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":0,"requires":[],"url":"/producten/dienst-sla-zilver"}'::jsonb),
  ('FA-DNS-SLA-G', 'Support-SLA Goud', 'Diensten', 0, 750, 14, '{"sku":"FA-DNS-SLA-G","slug":"dienst-sla-goud","productName":"Support-SLA Goud","category":"Diensten","tagline":"Eén uur, ook buiten kantoortijd","summary":"Reactie binnen een uur, zeven dagen per week, met een telefoonnummer dat buiten kantoortijd wordt opgenomen.","priceOnce":0,"priceMonthly":750,"priceLabel":"€ 750 per maand","availability":"wachtlijst","availabilityLabel":"Wachtlijst","leadTimeDays":14,"requires":[],"url":"/producten/dienst-sla-goud"}'::jsonb),
  ('FA-DNS-ONDH', 'Beleidsonderhoud', 'Diensten', 1, 400, 0, '{"sku":"FA-DNS-ONDH","slug":"dienst-beleidsonderhoud","productName":"Beleidsonderhoud","category":"Diensten","tagline":"Maandelijks bijsturen op wat je team corrigeert","summary":"Wij kijken elke maand naar de correcties en passen het beleid aan. Zonder dit blijft de agent staan waar hij bij oplevering stond.","priceOnce":0,"priceMonthly":400,"priceLabel":"€ 400 per maand","availability":"direct","availabilityLabel":"Direct beschikbaar","leadTimeDays":0,"requires":[],"url":"/producten/dienst-beleidsonderhoud"}'::jsonb)
on conflict (sku) do update set
  product_name=excluded.product_name, category=excluded.category,
  in_stock=excluded.in_stock, unit_value=excluded.unit_value,
  lead_time_days=excluded.lead_time_days, data=excluded.data;

-- Wat niet meer in de catalogus staat, hoort de agent ook niet meer te vinden.
delete from public.demo_inventory where sku not in ('FA-AGT-MAIL', 'FA-AGT-CHAT', 'FA-AGT-WA', 'FA-AGT-DOC', 'FA-AGT-TEL', 'FA-KOP-M365', 'FA-KOP-GWS', 'FA-KOP-WOO', 'FA-KOP-SHOP', 'FA-KOP-EOL', 'FA-KOP-HUB', 'FA-KOP-PIPE', 'FA-KOP-STRP', 'FA-KOP-MOL', 'FA-KOP-TRACK', 'FA-KOP-KVK', 'FA-KOP-CUST', 'FA-MOD-BAK', 'FA-MOD-KB', 'FA-MOD-TIC', 'FA-MOD-RAP', 'FA-MOD-AUD', 'FA-MOD-LANG', 'FA-MOD-SSO', 'FA-DNS-DISC', 'FA-DNS-IMPL', 'FA-DNS-TRAIN', 'FA-DNS-SLA-Z', 'FA-DNS-SLA-G', 'FA-DNS-ONDH');

-- ---------------------------------------------------------------------------
-- Implementatietrajecten (de "orders" waarop de agent kan zoeken)
-- ---------------------------------------------------------------------------
insert into public.demo_orders
  (order_number, customer_email, customer_name, status, total_value, currency,
   carrier, tracking_code, data)
values
  ('DEMO-1001', 'j.dekker@example.com', 'Jeroen Dekker', 'shipped', 5700, 'EUR',
   'Sanne', 'IMPL-1001',
   '{"orderNumber":"DEMO-1001","customerEmail":"j.dekker@example.com","customerName":"Jeroen Dekker","company":"Dekker Interieur","orderDate":"2026-07-28T09:00:00Z","status":"shipped","phase":"Inrichting","nextStep":"Meeloopfase start maandag; het team ziet dan concepten zonder dat er iets uitgaat.","consultant":"Sanne","projectCode":"IMPL-1001","items":[{"sku":"FA-AGT-MAIL","productName":"Mailagent","priceOnce":4500,"priceMonthly":750},{"sku":"FA-KOP-M365","productName":"Microsoft 365 / Exchange","priceOnce":1200,"priceMonthly":0}],"oneOffTotal":5700,"monthlyTotal":750,"currency":"EUR"}'::jsonb),
  ('DEMO-1002', 'm.vandenberg@example.com', 'Marieke van den Berg', 'delivered', 4000, 'EUR',
   'Sanne', 'IMPL-1002',
   '{"orderNumber":"DEMO-1002","customerEmail":"m.vandenberg@example.com","customerName":"Marieke van den Berg","company":"Van den Berg Wonen","orderDate":"2026-06-15T09:00:00Z","status":"delivered","phase":"Live","nextStep":"Maandelijkse bijsturing op basis van de correcties van het team.","consultant":"Sanne","projectCode":"IMPL-1002","items":[{"sku":"FA-AGT-CHAT","productName":"Chatbot","priceOnce":2500,"priceMonthly":450},{"sku":"FA-MOD-KB","productName":"Kennisbank","priceOnce":1500,"priceMonthly":250}],"oneOffTotal":4000,"monthlyTotal":700,"currency":"EUR"}'::jsonb),
  ('DEMO-1003', 'p.jansen@example.com', 'Peter Jansen', 'pending', 1500, 'EUR',
   null, null,
   '{"orderNumber":"DEMO-1003","customerEmail":"p.jansen@example.com","customerName":"Peter Jansen","company":"Jansen Techniek","orderDate":"2026-08-11T09:00:00Z","status":"pending","phase":"Wacht op aftrap","nextStep":"Aftrapgesprek inplannen; daarna twee weken tot oplevering.","consultant":null,"projectCode":null,"items":[{"sku":"FA-MOD-KB","productName":"Kennisbank","priceOnce":1500,"priceMonthly":250},{"sku":"FA-MOD-TIC","productName":"Ticketing","priceOnce":0,"priceMonthly":200}],"oneOffTotal":1500,"monthlyTotal":450,"currency":"EUR"}'::jsonb)
on conflict (order_number) do update set
  customer_email=excluded.customer_email, customer_name=excluded.customer_name,
  status=excluded.status, total_value=excluded.total_value,
  currency=excluded.currency, carrier=excluded.carrier,
  tracking_code=excluded.tracking_code, data=excluded.data;

delete from public.demo_orders where order_number not in ('DEMO-1001', 'DEMO-1002', 'DEMO-1003');

-- ---------------------------------------------------------------------------
-- Mijlpalen per traject (waar bij een fysieke shop de tracking zou staan)
-- ---------------------------------------------------------------------------
insert into public.demo_order_tracking (tracking_code, carrier, current_status, data)
values
  ('IMPL-1001', 'Sanne', 'Inrichting',
   '{"trackingCode":"IMPL-1001","projectCode":"IMPL-1001","consultant":"Sanne","currentStatus":"Inrichting","lastMilestone":"Beleid ingericht","nextStep":"Meeloopfase start maandag; het team ziet dan concepten zonder dat er iets uitgaat.","events":[{"timestamp":"2026-07-29T10:00:00Z","status":"Discovery afgerond","location":"Elf categorieën vastgesteld"},{"timestamp":"2026-08-04T10:00:00Z","status":"Mailkoppeling live","location":"Gedeelde mailbox aangesloten"},{"timestamp":"2026-08-12T10:00:00Z","status":"Beleid ingericht","location":"Concepten worden gegenereerd"}]}'::jsonb),
  ('IMPL-1002', 'Sanne', 'Live',
   '{"trackingCode":"IMPL-1002","projectCode":"IMPL-1002","consultant":"Sanne","currentStatus":"Live","lastMilestone":"Eerste bijsturing","nextStep":"Maandelijkse bijsturing op basis van de correcties van het team.","events":[{"timestamp":"2026-06-20T10:00:00Z","status":"Kennisbank gevuld","location":"340 documenten, opgeschoond"},{"timestamp":"2026-07-01T10:00:00Z","status":"Widget live","location":"Op de webshop geplaatst"},{"timestamp":"2026-07-15T10:00:00Z","status":"Eerste bijsturing","location":"Retourbeleid aangescherpt"}]}'::jsonb)
on conflict (tracking_code) do update set
  carrier=excluded.carrier, current_status=excluded.current_status,
  data=excluded.data;

delete from public.demo_order_tracking where tracking_code not in ('IMPL-1001', 'IMPL-1002');

-- ---------------------------------------------------------------------------
-- Klanten
-- ---------------------------------------------------------------------------
insert into public.demo_customers (email, name, data) values
  ('j.dekker@example.com', 'Jeroen Dekker', '{"email":"j.dekker@example.com","name":"Jeroen Dekker","company":"Dekker Interieur","orderCount":1}'::jsonb),
  ('m.vandenberg@example.com', 'Marieke van den Berg', '{"email":"m.vandenberg@example.com","name":"Marieke van den Berg","company":"Van den Berg Wonen","orderCount":1}'::jsonb),
  ('p.jansen@example.com', 'Peter Jansen', '{"email":"p.jansen@example.com","name":"Peter Jansen","company":"Jansen Techniek","orderCount":1}'::jsonb)
on conflict (email) do update set name=excluded.name, data=excluded.data;

delete from public.demo_customers where email not in ('j.dekker@example.com', 'm.vandenberg@example.com', 'p.jansen@example.com');
